---
# handlers file for roles/mariadb
#
- name: start mariadb
  service:
    name: mariadb
    state: started 
    enabled: yes

- name: stop mariadb
  service:
    name: mariadb
    state: stopped 

- name: start xinetd 
  service:
    name: xinetd
    state: restarted 
    enabled: yes
